"""Add free kickin option

Revision ID: e3909f0be018
Revises: e5d885afba92
Create Date: 2016-05-26 07:59:32.873845

"""

# revision identifiers, used by Alembic.
revision = 'e3909f0be018'
down_revision = 'e5d885afba92'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('free_kickin', sa.Boolean(), server_default='False', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendee', 'free_kickin')
    ### end Alembic commands ###
